export const EDITOR_ASSET_BASE = '/editor-assets/';

export const EDITOR_BOOTSTRAP_SCRIPTS = [
  '/editor-assets/preferences.js',
  '/editor-assets/theme-registry.js',
  '/editor-assets/theme-service.js',
  '/editor-assets/theme-canvas.js',
  '/editor-assets/locale-service.js',
  '/editor-assets/locale-ru.js',
  '/editor-assets/appearance-service.js',
] as const;

export const EDITOR_STYLESHEETS = [
  'main.css',
  'replicate-theme.css',
  'mt-track-color-frames.css',
  'mt-infinite-grid.css',
  'ui-bugfixes.css',
  'mt-grid-soft.css',
  'mt-background-grid.css',
  'selection-badge.css',
  'interaction-cursors.css',
  'animation-system.css',
  'toolbar-badges-icons.css',
  'tooltip-layer.css',
  'mt-add-channel-bottom.css',
  'floating-safe-placement.css',
  'menu-dialog-chain.css',
  'timeline-extra-scroll.css',
  'toolbar-fluid-fix.css',
  'selection-panel-final-fix.css',
  'marker-head-centering.css',
  'toolbar-icons-restore.css',
  'composition-waveform-badge.css',
  'toolbar-time-transport-final-fix.css',
  'time-badge-no-crop.css',
  'mt-scroll-ruler-final-fix.css',
  'selection-panel-responsive-fix.css',
  'marker-create-button.css',
  'clip-rename-button.css',
  'appearance.css',
  'theme-overrides.css',
] as const;

export const EDITOR_RUNTIME_SCRIPTS = [
  'dist/wavesurfer.js',
  'dist/plugin/wavesurfer.regions.js',
  '/editor-assets/notification-service.js',
  '/editor-assets/app.js',
  '/editor-assets/keys.js',
  '/editor-assets/markers.js',
  '/editor-assets/contextmenu.js',
  '/editor-assets/loudness-analysis.js',
  '/editor-assets/menu-check-service.js',
  '/editor-assets/ui-fx.js',
  '/editor-assets/ui.js',
  '/editor-assets/modal.js',
  '/editor-assets/state.js',
  '/editor-assets/engine.js',
  '/editor-assets/audio-effect-utilities.js',
  '/editor-assets/audio-buffer-operations.js',
  '/editor-assets/actions.js',
  '/editor-assets/drag.js',
  '/editor-assets/recorder.js',
  '/editor-assets/welcome-service.js',
  '/editor-assets/fx-pg-eq.js',
  '/editor-assets/fx-auto.js',
  '/editor-assets/local-session-store.js',
  '/editor-assets/metadata-service.js',
  'lzma.js',
  '/editor-assets/amss-format.js',
  '/editor-assets/multitrack.js',
  '/editor-assets/composition-waveform-service.js',
  '/editor-assets/multitrack-scroll-service.js',
  '/editor-assets/marker-toolbar-service.js',
  '/editor-assets/clip-rename-toolbar-service.js',
  '/editor-assets/single-waveform-view-service.js',
  '/editor-assets/touch-clip-selection-service.js',
  '/editor-assets/settings-trigger-service.js',
  '/editor-assets/next-bridge.js',
] as const;

export function editorAssetPath(asset: string) {
  return asset.startsWith('/') ? asset : `${EDITOR_ASSET_BASE}${asset}`;
}
