export const EDITOR_ASSET_BASE = '/editor-assets/';

export const EDITOR_BOOTSTRAP_SCRIPTS = [
  '/editor-assets/preferences.js',
  'theme-registry.js',
  '/editor-assets/theme-service.js',
  'theme-canvas.js',
  '/editor-assets/locale-service.js',
  'locale-ru.js',
  'appearance.js',
] as const;

export const EDITOR_STYLESHEETS = [
  'main.css',
  'replicate-theme.css',
  'mt-track-color-frames.css',
  'mt-infinite-grid.css',
  'ui-bugfixes.css',
  'mt-grid-soft.css',
  'mt-background-grid.css',
  'selection-badge.css',
  'interaction-cursors.css',
  'animation-system.css',
  'toolbar-badges-icons.css',
  'tooltip-layer.css',
  'mt-add-channel-bottom.css',
  'floating-safe-placement.css',
  'menu-dialog-chain.css',
  'timeline-extra-scroll.css',
  'toolbar-fluid-fix.css',
  'selection-panel-final-fix.css',
  'marker-head-centering.css',
  'toolbar-icons-restore.css',
  'composition-waveform-badge.css',
  'toolbar-time-transport-final-fix.css',
  'time-badge-no-crop.css',
  'mt-scroll-ruler-final-fix.css',
  'selection-panel-responsive-fix.css',
  'marker-create-button.css',
  'clip-rename-button.css',
  'appearance.css',
  'theme-overrides.css',
] as const;

export const EDITOR_RUNTIME_SCRIPTS = [
  'dist/wavesurfer.js',
  'dist/plugin/wavesurfer.regions.js',
  'oneup.js',
  'app.js',
  'keys.js',
  'markers.js',
  'contextmenu.js',
  '/editor-assets/loudness-analysis.js',
  'menu-check-svg.js',
  'ui-fx.js',
  'ui.js',
  'modal.js',
  'state.js',
  'engine.js',
  '/editor-assets/audio-effect-utilities.js',
  '/editor-assets/audio-buffer-operations.js',
  'actions.js',
  'drag.js',
  'recorder.js',
  'welcome.js',
  'fx-pg-eq.js',
  'fx-auto.js',
  '/editor-assets/local-session-store.js',
  'id3.js',
  'lzma.js',
  '/editor-assets/amss-format.js',
  'multitrack.js',
  'composition-waveform-badge.js',
  'mt-scroll-ruler-final-fix.js',
  'marker-create-button.js',
  'clip-rename-button.js',
  'touch-clip-select-fix.js',
  'settings-trigger.js',
  '/editor-assets/next-bridge.js',
] as const;

export function editorAssetPath(asset: string) {
  return asset.startsWith('/') ? asset : `${EDITOR_ASSET_BASE}${asset}`;
}
