import type { EditorLocale } from '@/lib/editor-preferences';

const EDITOR_COPY = {
  en: {
    cancel: 'Cancel',
    close: 'Close',
    colorTheme: 'Color theme',
    copy: 'Copy',
    cut: 'Cut',
    deleteSelection: 'Delete',
    dock: 'DOCK',
    dragPanel: 'Drag panel',
    editorDescription: 'Browser-first multitrack audio editor and waveform workstation.',
    editorTitle: 'Editor',
    editing: 'Editing',
    effects: 'Effects',
    effect: 'Effect',
    effectApply: 'Apply effect',
    effectBuiltInPreset: 'Built-in preset',
    effectCancelPreview: 'Stop preview',
    effectCompressor: 'Compressor',
    effectDelay: 'Delay',
    effectDistortion: 'Distortion',
    effectGain: 'Gain',
    effectGraphicEqualizer: 'Graphic equalizer',
    effectHardLimiter: 'Hard limiter',
    effectLinked: 'Normalize channels equally',
    effectMode: 'Mode',
    effectModeLufs: 'Integrated loudness (LUFS)',
    effectModePeak: 'Peak',
    effectModeRms: 'RMS',
    effectNormalize: 'Normalize',
    effectParameterAttack: 'Attack',
    effectParameterAmount: 'Target level',
    effectParameterBandGains: 'Band gains',
    effectParameterDecay: 'Decay',
    effectParameterDelayTime: 'Delay time',
    effectParameterFeedback: 'Feedback',
    effectParameterHard: 'Hard limiting',
    effectParameterKnee: 'Knee',
    effectParameterLimit: 'Limit to',
    effectParameterLookAhead: 'Look ahead',
    effectParameterLowHighRatio: 'Low/high ratio',
    effectParameterMakeup: 'Makeup',
    effectParameterRatio: 'Ratio',
    effectParameterRelease: 'Release',
    effectParameterThreshold: 'Threshold',
    effectParameterTime: 'Reverb time',
    effectParameterWet: 'Wet',
    effectPeakCeiling: 'Peak ceiling',
    effectPresetName: 'Preset name',
    effectPreview: 'Preview',
    effectReverb: 'Reverb',
    effectSavePreset: 'Save preset',
    effectSelectRange: 'Select an audio range to preview or apply an effect.',
    effectTargetLufs: 'Target loudness',
    exportFailed: 'Could not export audio.',
    exportWav: 'Export WAV',
    frequencyAnalyser: 'FREQUENCY ANALYSER',
    language: 'Language',
    loadingEditor: 'Loading audio editor…',
    nativeEditorTitle: 'Framework-native AudioMass editor',
    openAudio: 'Open audio',
    insertSilence: 'Insert silence',
    paste: 'Paste',
    pause: 'Pause',
    play: 'Play',
    dropAudio: 'Drop an audio file here or use “Open audio”.',
    markers: 'Markers',
    markerName: 'Marker name',
    addAtCursor: 'Add at cursor',
    removeMarker: 'Remove marker',
    redo: 'Redo',
    state: 'State',
    timeline: 'Timeline',
    transport: 'Transport',
    playbackPosition: 'Playback position',
    sampleRate: 'Sample rate',
    selectAll: 'Select all',
    selectionEnd: 'Selection end',
    selectionStart: 'Selection start',
    setSelection: 'Set selection',
    silenceDuration: 'Silence, seconds',
    stop: 'Stop',
    trimSelection: 'Trim to selection',
    undo: 'Undo',
    volume: 'Volume',
    wavBitDepth: 'WAV format',
    multitrackMixer: 'Multitrack mixer',
    openMultitrack: 'OPEN MULTITRACK',
    preferencesDescription: 'Changes are applied to the production editor workspace.',
    return: 'RETURN',
    save: 'Save',
    settingsTitle: 'Editor settings',
    spectralAnalyser: 'SPECTRAL ANALYSER',
    window: 'WINDOW',
  },
  ru: {
    cancel: 'Отмена',
    close: 'Закрыть',
    colorTheme: 'Цветовая тема',
    copy: 'Копировать',
    cut: 'Вырезать',
    deleteSelection: 'Удалить',
    dock: 'ОКНО',
    dragPanel: 'Перетащить панель',
    editorDescription: 'Мультитрековый аудиоредактор и рабочая станция для звуковой волны.',
    editorTitle: 'Редактор',
    editing: 'Редактирование',
    effects: 'Эффекты',
    effect: 'Эффект',
    effectApply: 'Применить эффект',
    effectBuiltInPreset: 'Встроенный пресет',
    effectCancelPreview: 'Остановить предпрослушивание',
    effectCompressor: 'Компрессор',
    effectDelay: 'Задержка',
    effectDistortion: 'Дисторшн',
    effectGain: 'Усиление',
    effectGraphicEqualizer: 'Графический эквалайзер',
    effectHardLimiter: 'Жёсткий лимитер',
    effectLinked: 'Нормализовать каналы одинаково',
    effectMode: 'Режим',
    effectModeLufs: 'Интегральная громкость (LUFS)',
    effectModePeak: 'Пик',
    effectModeRms: 'RMS',
    effectNormalize: 'Нормализация',
    effectParameterAttack: 'Атака',
    effectParameterAmount: 'Целевой уровень',
    effectParameterBandGains: 'Усиление полос',
    effectParameterDecay: 'Затухание',
    effectParameterDelayTime: 'Время задержки',
    effectParameterFeedback: 'Обратная связь',
    effectParameterHard: 'Жёсткое ограничение',
    effectParameterKnee: 'Колено',
    effectParameterLimit: 'Ограничить до',
    effectParameterLookAhead: 'Опережение',
    effectParameterLowHighRatio: 'Соотношение тихих/громких',
    effectParameterMakeup: 'Компенсация',
    effectParameterRatio: 'Соотношение',
    effectParameterRelease: 'Восстановление',
    effectParameterThreshold: 'Порог',
    effectParameterTime: 'Время реверберации',
    effectParameterWet: 'Обработанный сигнал',
    effectPeakCeiling: 'Ограничение пика',
    effectPresetName: 'Название пресета',
    effectPreview: 'Предпрослушать',
    effectReverb: 'Реверберация',
    effectSavePreset: 'Сохранить пресет',
    effectSelectRange: 'Выделите участок аудио для предпрослушивания или применения эффекта.',
    effectTargetLufs: 'Целевая громкость',
    exportFailed: 'Не удалось экспортировать аудио.',
    exportWav: 'Экспорт WAV',
    frequencyAnalyser: 'ЧАСТОТНЫЙ АНАЛИЗАТОР',
    language: 'Язык',
    loadingEditor: 'Загрузка аудиоредактора…',
    nativeEditorTitle: 'Модульный редактор AudioMass',
    openAudio: 'Открыть аудио',
    insertSilence: 'Вставить тишину',
    paste: 'Вставить',
    pause: 'Пауза',
    play: 'Воспроизвести',
    dropAudio: 'Перетащите сюда аудиофайл или нажмите «Открыть аудио».',
    markers: 'Маркеры',
    markerName: 'Название маркера',
    addAtCursor: 'Добавить у курсора',
    removeMarker: 'Удалить маркер',
    redo: 'Повторить',
    state: 'Состояние',
    timeline: 'Шкала времени',
    transport: 'Транспорт',
    playbackPosition: 'Позиция воспроизведения',
    sampleRate: 'Частота дискретизации',
    selectAll: 'Выделить всё',
    selectionEnd: 'Конец выделения',
    selectionStart: 'Начало выделения',
    setSelection: 'Задать выделение',
    silenceDuration: 'Тишина, секунд',
    stop: 'Стоп',
    trimSelection: 'Обрезать по выделению',
    undo: 'Отменить',
    volume: 'Громкость',
    wavBitDepth: 'Формат WAV',
    multitrackMixer: 'Мультитрековый микшер',
    openMultitrack: 'ОТКРОЙТЕ МУЛЬТИТРЕК',
    preferencesDescription: 'Параметры применяются к рабочей области production-редактора.',
    return: 'ВЕРНУТЬ',
    save: 'Сохранить',
    settingsTitle: 'Настройки редактора',
    spectralAnalyser: 'СПЕКТРАЛЬНЫЙ АНАЛИЗАТОР',
    window: 'ОКНО',
  },
} as const;

export type EditorCopyKey = keyof (typeof EDITOR_COPY)['en'];

export function editorCopy(locale: EditorLocale, key: EditorCopyKey) {
  return EDITOR_COPY[locale][key];
}
