import type { EditorLocale } from '@/lib/editor-preferences';

const EDITOR_COPY = {
  en: {
    cancel: 'Cancel',
    close: 'Close',
    colorTheme: 'Color theme',
    dock: 'DOCK',
    dragPanel: 'Drag panel',
    editorDescription: 'Browser-first multitrack audio editor and waveform workstation.',
    editorTitle: 'Editor',
    frequencyAnalyser: 'FREQUENCY ANALYSER',
    language: 'Language',
    loadingEditor: 'Loading audio editor…',
    nativeEditorTitle: 'Framework-native AudioMass editor',
    openAudio: 'Open audio',
    play: 'Play',
    pause: 'Pause',
    undo: 'Undo',
    redo: 'Redo',
    dropAudio: 'Drop an audio file here or use “Open audio”.',
    markers: 'Markers',
    markerName: 'Marker name',
    addAtCursor: 'Add at cursor',
    removeMarker: 'Remove marker',
    state: 'State',
    timeline: 'Timeline',
    transport: 'Transport',
    playbackPosition: 'Playback position',
    sampleRate: 'Sample rate',
    multitrackMixer: 'Multitrack mixer',
    openMultitrack: 'OPEN MULTITRACK',
    preferencesDescription: 'Changes are applied to the production editor workspace.',
    return: 'RETURN',
    save: 'Save',
    settingsTitle: 'Editor settings',
    spectralAnalyser: 'SPECTRAL ANALYSER',
    window: 'WINDOW',
  },
  ru: {
    cancel: 'Отмена',
    close: 'Закрыть',
    colorTheme: 'Цветовая тема',
    dock: 'ОКНО',
    dragPanel: 'Перетащить панель',
    editorDescription: 'Мультитрековый аудиоредактор и рабочая станция для звуковой волны.',
    editorTitle: 'Редактор',
    frequencyAnalyser: 'ЧАСТОТНЫЙ АНАЛИЗАТОР',
    language: 'Язык',
    loadingEditor: 'Загрузка аудиоредактора…',
    nativeEditorTitle: 'Модульный редактор AudioMass',
    openAudio: 'Открыть аудио',
    play: 'Воспроизвести',
    pause: 'Пауза',
    undo: 'Отменить',
    redo: 'Повторить',
    dropAudio: 'Перетащите сюда аудиофайл или нажмите «Открыть аудио».',
    markers: 'Маркеры',
    markerName: 'Название маркера',
    addAtCursor: 'Добавить у курсора',
    removeMarker: 'Удалить маркер',
    state: 'Состояние',
    timeline: 'Шкала времени',
    transport: 'Транспорт',
    playbackPosition: 'Позиция воспроизведения',
    sampleRate: 'Частота дискретизации',
    multitrackMixer: 'Мультитрековый микшер',
    openMultitrack: 'ОТКРОЙТЕ МУЛЬТИТРЕК',
    preferencesDescription: 'Параметры применяются к рабочей области production-редактора.',
    return: 'ВЕРНУТЬ',
    save: 'Сохранить',
    settingsTitle: 'Настройки редактора',
    spectralAnalyser: 'СПЕКТРАЛЬНЫЙ АНАЛИЗАТОР',
    window: 'ОКНО',
  },
} as const;

export type EditorCopyKey = keyof (typeof EDITOR_COPY)['en'];

export function editorCopy(locale: EditorLocale, key: EditorCopyKey) {
  return EDITOR_COPY[locale][key];
}
