import type { CSSProperties } from 'react';

import type { EditorTheme } from '@/lib/editor-preferences';

export interface EditorThemeDefinition {
  accent: string;
  accentAlt: string;
  background: string;
  danger: string;
  id: EditorTheme;
  mode: 'dark' | 'light';
  solo: string;
  success: string;
  surface1: string;
  surface2: string;
  surface3: string;
  surface4: string;
  text: string;
  textMuted: string;
  textSubtle: string;
  warning: string;
}

const EDITOR_THEME_DEFINITIONS: Record<EditorTheme, EditorThemeDefinition> = {
  replicate: {
    accent: '#43e4dc',
    accentAlt: '#8ef1ec',
    background: '#050607',
    danger: '#ff4d5e',
    id: 'replicate',
    mode: 'dark',
    solo: '#b993ff',
    success: '#34d399',
    surface1: '#080a0d',
    surface2: '#0c0f12',
    surface3: '#12171d',
    surface4: '#1b222b',
    text: '#f6f7f8',
    textMuted: '#b2bcc8',
    textSubtle: '#7b8694',
    warning: '#facc15',
  },
  dracula: {
    accent: '#bd93f9',
    accentAlt: '#ff79c6',
    background: '#191a21',
    danger: '#ff5555',
    id: 'dracula',
    mode: 'dark',
    solo: '#8be9fd',
    success: '#50fa7b',
    surface1: '#21222c',
    surface2: '#282a36',
    surface3: '#343746',
    surface4: '#44475a',
    text: '#f8f8f2',
    textMuted: '#c6c8d1',
    textSubtle: '#85889a',
    warning: '#f1fa8c',
  },
  nord: {
    accent: '#88c0d0',
    accentAlt: '#8fbcbb',
    background: '#242933',
    danger: '#bf616a',
    id: 'nord',
    mode: 'dark',
    solo: '#b48ead',
    success: '#a3be8c',
    surface1: '#2e3440',
    surface2: '#3b4252',
    surface3: '#434c5e',
    surface4: '#4c566a',
    text: '#eceff4',
    textMuted: '#d8dee9',
    textSubtle: '#8793a5',
    warning: '#ebcb8b',
  },
  'tokyo-night': {
    accent: '#7aa2f7',
    accentAlt: '#2ac3de',
    background: '#16161e',
    danger: '#f7768e',
    id: 'tokyo-night',
    mode: 'dark',
    solo: '#bb9af7',
    success: '#9ece6a',
    surface1: '#1a1b26',
    surface2: '#202334',
    surface3: '#292e42',
    surface4: '#3b4261',
    text: '#c0caf5',
    textMuted: '#a9b1d6',
    textSubtle: '#737da1',
    warning: '#e0af68',
  },
  catppuccin: {
    accent: '#cba6f7',
    accentAlt: '#89b4fa',
    background: '#11111b',
    danger: '#f38ba8',
    id: 'catppuccin',
    mode: 'dark',
    solo: '#94e2d5',
    success: '#a6e3a1',
    surface1: '#181825',
    surface2: '#1e1e2e',
    surface3: '#313244',
    surface4: '#45475a',
    text: '#cdd6f4',
    textMuted: '#bac2de',
    textSubtle: '#7f849c',
    warning: '#f9e2af',
  },
  'one-dark': {
    accent: '#61afef',
    accentAlt: '#56b6c2',
    background: '#17191f',
    danger: '#e06c75',
    id: 'one-dark',
    mode: 'dark',
    solo: '#c678dd',
    success: '#98c379',
    surface1: '#1e2127',
    surface2: '#282c34',
    surface3: '#323842',
    surface4: '#3e4451',
    text: '#abb2bf',
    textMuted: '#9da5b4',
    textSubtle: '#6f7785',
    warning: '#e5c07b',
  },
  gruvbox: {
    accent: '#fabd2f',
    accentAlt: '#83a598',
    background: '#1d2021',
    danger: '#fb4934',
    id: 'gruvbox',
    mode: 'dark',
    solo: '#d3869b',
    success: '#b8bb26',
    surface1: '#282828',
    surface2: '#32302f',
    surface3: '#3c3836',
    surface4: '#504945',
    text: '#ebdbb2',
    textMuted: '#d5c4a1',
    textSubtle: '#928374',
    warning: '#fe8019',
  },
  'solarized-dark': {
    accent: '#2aa198',
    accentAlt: '#268bd2',
    background: '#002b36',
    danger: '#dc322f',
    id: 'solarized-dark',
    mode: 'dark',
    solo: '#6c71c4',
    success: '#859900',
    surface1: '#073642',
    surface2: '#0b3f4a',
    surface3: '#174b55',
    surface4: '#285a63',
    text: '#eee8d5',
    textMuted: '#93a1a1',
    textSubtle: '#657b83',
    warning: '#b58900',
  },
  'github-light': {
    accent: '#0969da',
    accentAlt: '#0550ae',
    background: '#f6f8fa',
    danger: '#cf222e',
    id: 'github-light',
    mode: 'light',
    solo: '#8250df',
    success: '#1a7f37',
    surface1: '#ffffff',
    surface2: '#f3f4f6',
    surface3: '#eaeef2',
    surface4: '#d8dee4',
    text: '#1f2328',
    textMuted: '#57606a',
    textSubtle: '#6e7781',
    warning: '#9a6700',
  },
  'solarized-light': {
    accent: '#268bd2',
    accentAlt: '#2aa198',
    background: '#fdf6e3',
    danger: '#dc322f',
    id: 'solarized-light',
    mode: 'light',
    solo: '#6c71c4',
    success: '#859900',
    surface1: '#eee8d5',
    surface2: '#e6dfc9',
    surface3: '#ddd6c0',
    surface4: '#c9c2ad',
    text: '#073642',
    textMuted: '#586e75',
    textSubtle: '#839496',
    warning: '#b58900',
  },
};

function rgb(hex: string) {
  const value = hex.slice(1);
  const number = Number.parseInt(value.length === 3 ? value.replace(/(.)/g, '$1$1') : value, 16);
  return [(number >> 16) & 255, (number >> 8) & 255, number & 255] as const;
}

function alpha(hex: string, opacity: number) {
  const [red, green, blue] = rgb(hex);
  return `rgba(${red},${green},${blue},${opacity})`;
}

export function getEditorTheme(theme: EditorTheme): EditorThemeDefinition {
  return EDITOR_THEME_DEFINITIONS[theme];
}

export function editorThemeStyle(themeId: EditorTheme): CSSProperties {
  const theme = getEditorTheme(themeId);
  const light = theme.mode === 'light';
  const contrast = light ? '#ffffff' : theme.background;
  return {
    colorScheme: theme.mode,
    '--color-scheme': theme.mode,
    '--background': theme.background,
    '--foreground': theme.text,
    '--card': theme.surface1,
    '--card-foreground': theme.text,
    '--popover': theme.surface1,
    '--popover-foreground': theme.text,
    '--primary': theme.accent,
    '--primary-foreground': contrast,
    '--secondary': theme.surface2,
    '--secondary-foreground': theme.textMuted,
    '--muted': theme.surface2,
    '--muted-foreground': theme.textSubtle,
    '--accent': theme.surface3,
    '--accent-foreground': theme.text,
    '--destructive': theme.danger,
    '--destructive-foreground': light ? '#ffffff' : theme.background,
    '--border': alpha(theme.text, light ? 0.16 : 0.11),
    '--input': alpha(theme.text, 0.14),
    '--ring': theme.accent,
    '--bg-0': theme.background,
    '--bg-1': theme.surface1,
    '--bg-2': theme.surface2,
    '--bg-3': theme.surface3,
    '--bg-4': theme.surface4,
    '--fg-0': theme.text,
    '--fg-1': theme.textMuted,
    '--fg-2': theme.textSubtle,
    '--fg-3': alpha(theme.text, 0.32),
    '--ac': theme.accent,
    '--ac-2': theme.accentAlt,
    '--ac-soft': alpha(theme.accent, 0.12),
    '--ac-glow': alpha(theme.accent, 0.34),
    '--ac-ink': contrast,
    '--rec': theme.danger,
    '--rec-glow': alpha(theme.danger, 0.32),
    '--solo': theme.solo,
    '--solo-glow': alpha(theme.solo, 0.28),
    '--warn': theme.warning,
    '--ok': theme.success,
    '--pl': theme.warning,
    '--bd': alpha(theme.text, light ? 0.14 : 0.09),
    '--bd-s': alpha(theme.text, light ? 0.08 : 0.055),
    '--bd-h': alpha(theme.accent, 0.46),
    '--surface-translucent': alpha(theme.surface1, 0.94),
    '--surface-overlay': alpha(theme.background, 0.78),
    '--surface-hover': theme.surface3,
    '--surface-strong': theme.surface4,
    '--accent-contrast': contrast,
    '--accent-soft': alpha(theme.accent, 0.08),
    '--accent-muted': alpha(theme.accent, 0.18),
    '--accent-strong': alpha(theme.accent, 0.42),
    '--danger-contrast': light ? '#ffffff' : theme.background,
    '--danger-soft': alpha(theme.danger, 0.2),
    '--grid-color': alpha(theme.text, 0.055),
    '--grid-strong': alpha(theme.text, 0.18),
    '--shadow-color': light ? 'rgba(31,35,40,.18)' : 'rgba(0,0,0,.48)',
    '--wave-bg': theme.background,
    '--wave-color': theme.accentAlt,
    '--wave-progress': alpha(theme.danger, 0.24),
    '--timeline-bg': theme.surface1,
    '--timeline-fg': theme.textMuted,
    '--record-bg': theme.surface1,
    '--record-wave': theme.danger,
    '--marker-1': theme.success,
    '--marker-2': theme.accent,
    '--marker-3': theme.solo,
    '--marker-4': theme.warning,
    '--marker-5': theme.danger,
    '--marker-6': theme.accentAlt,
    '--editor-accent': theme.accent,
    '--editor-accent-alt': theme.accentAlt,
    '--editor-bg': theme.background,
    '--editor-border': theme.surface4,
    '--editor-danger': theme.danger,
    '--editor-panel': theme.surface2,
    '--editor-surface': theme.surface3,
    '--editor-text': theme.text,
    '--editor-text-muted': theme.textMuted,
    '--editor-waveform': theme.accentAlt,
  } as CSSProperties;
}
