import { validateEffectSchema, type BuiltInEffectPreset, type EffectSchema } from './schema.js';

function preset(
  id: string,
  name: string,
  values: BuiltInEffectPreset['values'],
): BuiltInEffectPreset {
  return { id, name, values };
}

const compressorPresets = [
  preset('vocal-lead', 'Vocal — Lead', {
    attack: 0.005,
    knee: 6,
    makeup: 6,
    ratio: 3,
    release: 0.15,
    threshold: -18,
  }),
  preset('vocal-broadcast', 'Vocal — Broadcast', {
    attack: 0.003,
    knee: 2,
    makeup: 7.5,
    ratio: 4,
    release: 0.1,
    threshold: -20,
  }),
  preset('drum-bus-glue', 'Drum Bus Glue', {
    attack: 0.03,
    knee: 3,
    makeup: 2.5,
    ratio: 2,
    release: 0.3,
    threshold: -10,
  }),
  preset('snare-punch', 'Snare Punch', {
    attack: 0.001,
    knee: 1,
    makeup: 5.5,
    ratio: 4,
    release: 0.06,
    threshold: -15,
  }),
  preset('kick-tighten', 'Kick Tighten', {
    attack: 0.01,
    knee: 2,
    makeup: 4.5,
    ratio: 4,
    release: 0.1,
    threshold: -12,
  }),
  preset('bass-even-out', 'Bass Even-Out', {
    attack: 0.015,
    knee: 4,
    makeup: 5,
    ratio: 3,
    release: 0.15,
    threshold: -15,
  }),
  preset('acoustic-smooth', 'Acoustic Smooth', {
    attack: 0.01,
    knee: 6,
    makeup: 5.5,
    ratio: 2.5,
    release: 0.15,
    threshold: -18,
  }),
  preset('master-glue', 'Master Glue', {
    attack: 0.03,
    knee: 6,
    makeup: 1.5,
    ratio: 1.5,
    release: 0.3,
    threshold: -8,
  }),
  preset('heavy-crush', 'Heavy Crush', {
    attack: 0.002,
    knee: 0,
    makeup: 8,
    ratio: 8,
    release: 0.1,
    threshold: -30,
  }),
  preset('brickwall-limit', 'Brickwall Limit', {
    attack: 0.001,
    knee: 0,
    makeup: 1.5,
    ratio: 20,
    release: 0.05,
    threshold: -3,
  }),
  preset('classic-3-1', 'Classic 3:1', {
    attack: 0.01,
    knee: 6,
    makeup: 6,
    ratio: 3,
    release: 0.1,
    threshold: -18,
  }),
  preset('light-touch', 'Light Touch', {
    attack: 0.005,
    knee: 2,
    makeup: 3,
    ratio: 2,
    release: 0.08,
    threshold: -12,
  }),
  preset('classic', 'Classic', {
    attack: 0.002,
    knee: 5,
    makeup: 12,
    ratio: 7,
    release: 0.1,
    threshold: -40,
  }),
  preset('dashed-distortion', 'Dashed Distortion', {
    attack: 0.233,
    knee: 26,
    makeup: 0,
    ratio: 2.05,
    release: 0,
    threshold: -45,
  }),
] as const;

const equalizerLabels = [
  '32 Hz',
  '64 Hz',
  '125 Hz',
  '250 Hz',
  '500 Hz',
  '1 kHz',
  '2 kHz',
  '4 kHz',
  '8 kHz',
  '16 kHz',
] as const;

const effectSchemas: readonly EffectSchema[] = [
  {
    builtInPresets: [
      preset('silence', 'Silence', { amount: 0 }),
      preset('minus-50', '-50%', { amount: 0.5 }),
      preset('minus-25', '-25%', { amount: 0.75 }),
      preset('plus-25', '+25%', { amount: 1.25 }),
      preset('plus-50', '+50%', { amount: 1.5 }),
      preset('plus-100', '+100%', { amount: 2 }),
    ],
    description: 'Multiply the selected audio amplitude.',
    id: 'gain',
    name: 'Gain',
    parameters: [
      {
        defaultValue: 1,
        id: 'amount',
        kind: 'number',
        label: 'Gain',
        maximum: 2.5,
        minimum: 0,
        step: 0.01,
        unit: '×',
      },
    ],
    preview: true,
  },
  {
    builtInPresets: compressorPresets,
    description: 'Reduce dynamic range with optional makeup gain.',
    id: 'compressor',
    name: 'Compressor',
    parameters: [
      {
        defaultValue: -24,
        id: 'threshold',
        kind: 'number',
        label: 'Threshold',
        maximum: 0,
        minimum: -100,
        step: 0.1,
        unit: 'dB',
      },
      {
        defaultValue: 30,
        id: 'knee',
        kind: 'number',
        label: 'Knee',
        maximum: 40,
        minimum: 0,
        step: 0.01,
        unit: 'dB',
      },
      {
        defaultValue: 12,
        id: 'ratio',
        kind: 'number',
        label: 'Ratio',
        maximum: 20,
        minimum: 1,
        step: 0.01,
        unit: ':1',
      },
      {
        defaultValue: 0.003,
        id: 'attack',
        kind: 'number',
        label: 'Attack',
        maximum: 1,
        minimum: 0,
        step: 0.001,
        unit: 's',
      },
      {
        defaultValue: 0.25,
        id: 'release',
        kind: 'number',
        label: 'Release',
        maximum: 1,
        minimum: 0,
        step: 0.001,
        unit: 's',
      },
      {
        defaultValue: 0,
        id: 'makeup',
        kind: 'number',
        label: 'Makeup',
        maximum: 24,
        minimum: -12,
        step: 0.1,
        unit: 'dB',
      },
    ],
    preview: true,
  },
  {
    builtInPresets: [
      preset('spotify', 'Spotify', {
        amount: 1,
        linked: true,
        mode: 'lufs',
        peakCeiling: -1,
        targetLufs: -14,
      }),
      preset('apple-music', 'Apple Music', {
        amount: 1,
        linked: true,
        mode: 'lufs',
        peakCeiling: -1,
        targetLufs: -16,
      }),
      preset('ebu-r128', 'Broadcast EBU R128', {
        amount: 1,
        linked: true,
        mode: 'lufs',
        peakCeiling: -1,
        targetLufs: -23,
      }),
    ],
    description: 'Normalize by peak, RMS, or integrated loudness.',
    id: 'normalize',
    name: 'Normalize',
    parameters: [
      {
        defaultValue: 'peak',
        id: 'mode',
        kind: 'select',
        label: 'Mode',
        options: [
          { id: 'peak', label: 'Peak' },
          { id: 'rms', label: 'RMS' },
          { id: 'lufs', label: 'LUFS' },
        ],
      },
      { defaultValue: false, id: 'linked', kind: 'boolean', label: 'Normalize L/R equally' },
      {
        defaultValue: 1,
        id: 'amount',
        kind: 'number',
        label: 'Normalize to',
        maximum: 2,
        minimum: 0,
        step: 0.01,
        unit: '×',
      },
      {
        defaultValue: -14,
        id: 'targetLufs',
        kind: 'number',
        label: 'Target loudness',
        maximum: -6,
        minimum: -40,
        step: 0.1,
        unit: 'LUFS',
      },
      {
        defaultValue: -1,
        id: 'peakCeiling',
        kind: 'number',
        label: 'Peak ceiling',
        maximum: 0,
        minimum: -6,
        step: 0.1,
        unit: 'dBTP',
      },
    ],
    preview: true,
  },
  {
    builtInPresets: [],
    description: 'Limit peaks with configurable look-ahead.',
    id: 'hard-limiter',
    name: 'Hard Limiter',
    parameters: [
      { defaultValue: false, id: 'hard', kind: 'boolean', label: 'Hard limiting' },
      {
        defaultValue: 0.99,
        id: 'limit',
        kind: 'number',
        label: 'Limit to',
        maximum: 1,
        minimum: 0.1,
        step: 0.01,
      },
      {
        defaultValue: 0,
        id: 'ratio',
        kind: 'number',
        label: 'Low/high ratio',
        maximum: 1,
        minimum: 0,
        step: 0.01,
      },
      {
        defaultValue: 10,
        id: 'lookAheadMs',
        kind: 'number',
        label: 'Look ahead',
        maximum: 500,
        minimum: 1,
        step: 0.01,
        unit: 'ms',
      },
    ],
    preview: true,
  },
  {
    builtInPresets: [
      preset('classic', 'Classic', { delaySeconds: 0.3, feedback: 0.4, mix: 0.4 }),
      preset('spacey', 'Spacey', { delaySeconds: 3, feedback: 0.6, mix: 0.3 }),
    ],
    description: 'Create a feedback delay.',
    id: 'delay',
    name: 'Delay',
    parameters: [
      {
        defaultValue: 0.28,
        id: 'delaySeconds',
        kind: 'number',
        label: 'Delay time',
        maximum: 6,
        minimum: 0,
        step: 0.01,
        unit: 's',
      },
      {
        defaultValue: 0.5,
        id: 'feedback',
        kind: 'number',
        label: 'Feedback',
        maximum: 1,
        minimum: 0,
        step: 0.01,
      },
      {
        defaultValue: 0.4,
        id: 'mix',
        kind: 'number',
        label: 'Wet',
        maximum: 1,
        minimum: 0,
        step: 0.01,
      },
    ],
    preview: true,
  },
  {
    builtInPresets: [],
    description: 'Apply a waveshaping distortion curve.',
    id: 'distortion',
    name: 'Distortion',
    parameters: [
      {
        defaultValue: 0.5,
        id: 'amount',
        kind: 'number',
        label: 'Gain',
        maximum: 2,
        minimum: 0,
        step: 0.01,
      },
    ],
    preview: true,
  },
  {
    builtInPresets: [
      preset('classic', 'Classic', { decay: 0.4, mix: 0.4, timeSeconds: 0.3 }),
      preset('spacey', 'Spacey', { decay: 0.6, mix: 0.3, timeSeconds: 3 }),
      preset('small-room', 'Small Room', { decay: 1.5, mix: 0.25, timeSeconds: 0.3 }),
      preset('medium-room', 'Medium Room', { decay: 1.2, mix: 0.35, timeSeconds: 0.7 }),
      preset('large-hall', 'Large Hall', { decay: 0.5, mix: 0.4, timeSeconds: 2.2 }),
      preset('cathedral', 'Cathedral', { decay: 0.3, mix: 0.5, timeSeconds: 3 }),
      preset('plate', 'Plate', { decay: 0.8, mix: 0.45, timeSeconds: 1.2 }),
      preset('vocal-booth', 'Vocal Booth', { decay: 2, mix: 0.2, timeSeconds: 0.5 }),
      preset('drum-chamber', 'Drum Chamber', { decay: 1, mix: 0.3, timeSeconds: 0.9 }),
      preset('ambient-wash', 'Ambient Wash', { decay: 0.2, mix: 0.6, timeSeconds: 2.8 }),
      preset('tight-slap', 'Tight Slap', { decay: 2.5, mix: 0.35, timeSeconds: 0.15 }),
      preset('cave', 'Cave', { decay: 0.4, mix: 0.55, timeSeconds: 2.5 }),
    ],
    description: 'Apply generated impulse-response reverb.',
    id: 'reverb',
    name: 'Reverb',
    parameters: [
      {
        defaultValue: 0.3,
        id: 'timeSeconds',
        kind: 'number',
        label: 'Time',
        maximum: 3,
        minimum: 0,
        step: 0.01,
        unit: 's',
      },
      {
        defaultValue: 0.05,
        id: 'decay',
        kind: 'number',
        label: 'Decay',
        maximum: 3,
        minimum: 0,
        step: 0.01,
      },
      {
        defaultValue: 0.6,
        id: 'mix',
        kind: 'number',
        label: 'Wet',
        maximum: 1,
        minimum: 0,
        step: 0.01,
      },
    ],
    preview: true,
  },
  {
    builtInPresets: [
      preset('reset', 'Reset', { gains: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0] }),
      preset('bass-boost', 'Bass Boost', { gains: [8, 7, 5, 2, 0, 0, 0, 0, 0, 0] }),
      preset('treble-boost', 'Treble Boost', { gains: [0, 0, 0, 0, 0, 0, 3, 5, 7, 8] }),
      preset('vocal-clarity', 'Vocal Clarity', {
        gains: [-8, -4, -2, -1, 1, 3, 5, 4, 2, 0],
      }),
      preset('podcast', 'Podcast', { gains: [-10, -6, -2, 0, 2, 3, 4, 3, 1, -2] }),
      preset('warm', 'Warm', { gains: [3, 4, 3, 2, 1, 0, -1, -2, -3, -4] }),
      preset('bright', 'Bright', { gains: [-2, -2, -2, -1, 0, 1, 3, 5, 6, 5] }),
      preset('v-shape', 'V-Shape', { gains: [6, 5, 3, 0, -2, -3, -2, 1, 4, 6] }),
    ],
    description: 'Ten-band graphical equalizer.',
    id: 'graphic-equalizer',
    name: 'Graphic Equalizer',
    parameters: [
      {
        defaultValue: new Array<number>(10).fill(0),
        id: 'gains',
        itemLabels: equalizerLabels,
        kind: 'number-list',
        label: 'Band gains',
        maximum: 25,
        minimum: -25,
        step: 0.01,
        unit: 'dB',
      },
    ],
    preview: true,
  },
  {
    builtInPresets: [],
    description: 'Create a seamless repeated loop from the selection.',
    id: 'seamless-loop',
    name: 'Seamless Loop',
    parameters: [
      {
        defaultValue: 10,
        id: 'crossfadeMs',
        kind: 'number',
        label: 'Crossfade',
        maximum: 500,
        minimum: 0,
        step: 1,
        unit: 'ms',
      },
      {
        defaultValue: 1,
        id: 'repeat',
        kind: 'number',
        label: 'Repeat loop',
        maximum: 64,
        minimum: 1,
        step: 1,
      },
      { defaultValue: false, id: 'trimSilence', kind: 'boolean', label: 'Trim edge silence' },
      {
        defaultValue: true,
        id: 'snapZeroCrossing',
        kind: 'boolean',
        label: 'Snap to zero crossing',
      },
    ],
    preview: true,
  },
];

export const EFFECT_SCHEMAS: readonly EffectSchema[] = effectSchemas.map(validateEffectSchema);

export function getEffectSchema(effectId: string): EffectSchema {
  const schema = EFFECT_SCHEMAS.find((candidate) => candidate.id === effectId);
  if (!schema) throw new TypeError(`Unknown effect: ${effectId}.`);
  return schema;
}
